In [1]:
from pickle import PERSID

import pandas as pd

data = [[1, 'a@b.com'], [2, 'c@d.com'], [3, 'a@b.com']]
person = pd.DataFrame(data, columns=['id', 'email']).astype({'id':'Int64', 'email':'object'})

In [5]:
person.loc[person.duplicated(subset=['email']), 'email'].rename('Email').drop_duplicates().to_frame()

In [9]:
person.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      3 non-null      Int64
 1   email   3 non-null      object
dtypes: Int64(1), object(1)
memory usage: 179.0+ bytes

In [43]:
df = pd.DataFrame([[1,2,3],[4,5,6]],columns=['id','x','y'])
df.set_index('id',inplace=True)
df.set_index('x',append=True)
df = pd.DataFrame([[1,2,3],[4,5,6]],columns=['id','x','y'])
df.set_index(['id','x'],inplace=True)

df.reset_index()
df
df.reset_index('x')
df.reset_index(1)

      y
id x
1  2  3
4  5  6

   id  x  y
0   1  2  3
1   4  5  6

      y
id x
1  2  3
4  5  6

    x  y
id
1   2  3
4   5  6

    x  y
id
1   2  3
4   5  6