In [51]:
import numpy as np
import pandas as pd

In [52]:
# 周考
# 第一题:
#读取表格 input.csv请完成下面题目，并添加注释说明。（pandas实现）
df = pd.read_csv('input.csv')
# 1. 请打印出，字段”Field_01“，每种值出现的次数。
df['Field_01'].value_counts()
# 2. 清洗”Field_02“，仅保留汉字，删除所有字母、数字于空白符（包含换行符）。
df['Field_02'] = df['Field_02'].str.replace(r'[^\u4e00-\u9fff]', '', regex=True)
# 3. 清洗”Field_03“，仅保留数字。
df['Field_03'] = df['Field_03'].str.replace(r'\D', '', regex=True)
# 4. 给”Field_05“赋值，值为”Field_04“中”s“出现的次数。
df['Field_05'] = df['Field_04'].str.count('s')
# 5. 删除序号为 4 的一行。
df.drop(df[df['序号'] == 4].index)  #, inplace=True)
# 6. 填充”Field_06“列中的空值为”W“。将最终结果保存为同级目录下的 input_r.csv
df['Field_06'].fillna('W')  #, inplace=True)
df.to_csv('input_r.csv', index=False)

Field_01
D    4
A    3
B    2
C    1
Name: count, dtype: int64

   序号 Field_01 Field_02 Field_03     Field_04  Field_05 Field_06 Field_07
0   1        A       信任              sdfdfnmg         1        w        w
1   2        B      随机词            sdssfgfdfg         3      NaN        w
2   3        D       得分             sdfdfssag         3        w        w
4   5        C      真实的      320    sdfdccxfg         1        w        w
5   6        D      才不会             sdfdfcccg         1        w        w
6   7        D      分隔符           sdfggssxdfg         3      NaN        w
7   8        B      换行符                sdfdfg         1        w        w
8   9        A     不该信任             sdfqqqdfg         1      NaN        w
9  10        D      在中国             sdfdggdfg         1        w        w

0    w
1    W
2    w
3    W
4    w
5    w
6    W
7    w
8    W
9    w
Name: Field_06, dtype: object

In [54]:
# 第二题:
# #读取表格 超市.xls请完成下面题目
df = pd.read_excel('超市.xls')
#1. 从 DataFrame 中选择 订单日期、销售额 和 利润 这三列。
df[['订单日期', '销售额', '利润']]
#2. 检查数据中'销售额'是否存在缺失值，如果有，将 销售额列的缺失值填充为 0。
# df['销售额'].isnull().any()
if df['销售额'].isnull().any():
    df['销售额'].fillna(0, inplace=True)
    print('销售额中的缺失值已填充0')
else:
    print('销售额没有缺失值')
#3. 检查数据中'数量'是否存在缺失值，如果有，将数量 列的缺失值填充为 0。
if df['数量'].isnull().any():
    df['数量'].fillna(0, inplace=True)
    print('数量中的缺失值已填充0')
else:
    print('数量没有缺失值')
#4. 按照 销售额 降序对数据进行排序。
df.sort_values('销售额', ascending=False)
#5. 按照 利润 降序对数据进行排序。
df.sort_values('利润', ascending=False)
#6. 筛选出 销售额 大于 100 且 利润 为正数的订单。
df.query('销售额>100 and 利润>0')
#7. 将 省/自治区 列重命名为 省份。
df.rename(columns={'省/自治区': '省份'})
#8. 将 装运模式 列中的 二级 替换为 二级配送。
df['装运模式'].replace('二级', '二级配送', inplace=True)
#9. 计算 销售额、数量 和 利润 之间的相关性矩阵。
df[['销售额', '数量', '利润']].corr()
#10. 筛选出 销售额 大于其均值加 3 倍标准差的订单数据。
df[df['销售额'] > df['销售额'].mean() + 3 * np.std(df['销售额'])]
#11. 筛选出 类别 为 “办公用品” 且 区域 为 “华东” 的订单，并计算这些订单的总 数量。
mask = df.query('类别=="办公用品" and 区域=="华东"')
mask['数量'].sum()

            订单日期       销售额        利润
0     2021-04-27   129.696   -60.704
1     2021-06-15   125.440    42.560
2     2021-06-15    31.920     4.200
3     2021-12-09   321.216   -27.104
4     2020-05-31  1375.920   550.200
...          ...       ...       ...
9954  2021-05-28   944.244  -314.916
9955  2021-05-28   447.720    35.560
9956  2021-05-28   239.988   -88.032
9957  2021-05-28  4851.588 -1617.392
9958  2018-12-02  7244.580 -3501.820

[9959 rows x 3 columns]

销售额没有缺失值
数量没有缺失值

,行 ID,订单 ID,订单日期,发货日期,装运模式,客户 ID,客户名称,细分,城市,省/自治区,国家/地区,区域,产品 ID,类别,子类别,产品名称,销售额,数量,折扣,利润
329,332,CN-2018-1182921,2018-05-13,2018-05-18,标准级,唐蔓-18010,唐蔓楚,公司,宣化,河北,中国,华北,家具-桌子-10001852,家具,桌子,"Bevis 会议桌, 组装",35621.355,11,0.25,-2375.065
1958,1975,CN-2021-2503468,2021-10-23,2021-10-28,二级,武明-18385,武明媚,消费者,北京,北京,中国,华北,办公用-器具-10000912,办公用品,器具,"Hamilton Beach 冰箱, 黑色",30306.640,13,0.00,908.180
964,967,CN-2020-5569845,2020-12-16,2020-12-22,标准级,彭娜-18550,彭娜,消费者,上海,上海,中国,华东,办公用-器具-10000373,办公用品,器具,"Breville 冰箱, 银色",29124.480,12,0.00,6115.200
3109,3128,CN-2018-3555396,2018-08-20,2018-08-22,二级,谭珊-19900,谭珊,消费者,上海,上海,中国,华东,技术-电话-10003828,技术,电话,"摩托罗拉 充电器, 混合尺寸",27112.680,9,0.00,3253.320
3362,3382,CN-2021-5844938,2021-10-19,2021-10-23,标准级,牛黎-16390,牛黎明,公司,洛阳,福建,中国,华东,技术-电话-10003828,技术,电话,"摩托罗拉 充电器, 混合尺寸",27112.680,9,0.00,3253.320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7107,7138,US-2020-2298972,2020-02-18,2020-02-24,标准级,郭升-20140,郭升,公司,通辽,内蒙古,中国,华北,办公用-美术-10001943,办公用品,美术,"Sanford 荧光笔, 金属",15.876,1,0.80,-45.304
6538,6564,CN-2021-1501002,2021-08-10,2021-08-12,二级,廖宣-20905,廖宣,消费者,睢城,江苏,中国,华东,办公用-美术-10002159,办公用品,美术,"BIC 钢笔, 金属",14.504,1,0.80,-23.296
2216,2234,US-2019-3964185,2019-01-30,2019-02-04,二级,佟斯-21025,佟斯云,小型企业,大连,辽宁,中国,东北,办公用-装订-10000765,办公用品,装订机,"Wilson Jones 孔加固材料, 回收",13.692,1,0.40,-8.708
4263,4284,CN-2019-4162714,2019-10-03,2019-10-05,一级,牛惠-14410,牛惠,小型企业,苏州,江苏,中国,华东,办公用-美术-10002634,办公用品,美术,"BIC 钢笔, 整包",13.580,1,0.80,-48.300
4592,4614,CN-2021-2052338,2021-08-03,2021-08-06,一级,邢伟-21505,邢伟,消费者,沙市,湖北,中国,中南,办公用-装订-10004840,办公用品,装订机,"Cardinal 孔加固材料, 透明",13.440,1,0.40,-6.580

,行 ID,订单 ID,订单日期,发货日期,装运模式,客户 ID,客户名称,细分,城市,省/自治区,国家/地区,区域,产品 ID,类别,子类别,产品名称,销售额,数量,折扣,利润
4907,4931,US-2019-4150614,2019-09-28,2019-10-01,一级,谷莲-16990,谷莲,公司,洛阳,河南,中国,中南,家具-椅子-10001258,家具,椅子,"Harbour Creations 扶手椅, 可调",25995.060,13,0.1,10108.280
8318,8355,CN-2018-5525339,2018-01-02,2018-01-07,二级,俞毅-12520,俞毅,消费者,江口,福建,中国,华东,技术-电话-10003187,技术,电话,"诺基亚 充电器, 混合尺寸",20871.060,7,0.0,9808.820
6786,6817,CN-2020-1599696,2020-06-24,2020-06-28,标准级,龙婷-21115,龙婷,公司,保定,河北,中国,华北,办公用-器具-10001757,办公用品,器具,"KitchenAid 炉灶, 黑色",23922.360,9,0.0,9329.040
3166,3185,US-2021-4339927,2021-12-15,2021-12-17,一级,秦淑-20440,秦淑芳,公司,龙泉,云南,中国,西南,家具-椅子-10004390,家具,椅子,"SAFCO 扶手椅, 每套两件",19474.560,9,0.0,9152.640
1708,1712,CN-2021-5552260,2021-05-08,2021-05-13,标准级,施菊-15040,施菊,消费者,平顶山,河南,中国,中南,技术-设备-10002958,技术,设备,"柯尼卡 喷墨打印机, 耐用",19022.640,13,0.0,9129.120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3206,3225,CN-2019-2306215,2019-03-22,2019-03-24,二级,陈晨-11095,陈晨,公司,广元,四川,中国,西南,技术-电话-10003828,技术,电话,"摩托罗拉 充电器, 混合尺寸",14460.096,8,0.4,-6748.224
3785,3806,US-2021-5726249,2021-12-24,2021-12-29,标准级,马惠-14335,马惠英,公司,兰溪,浙江,中国,华东,家具-桌子-10004719,家具,桌子,"Bevis 圆桌, 黑色",13542.032,14,0.6,-6771.408
3232,3251,CN-2021-2964244,2021-11-06,2021-11-10,二级,肖崆-15520,肖崆,消费者,枝城,浙江,中国,华东,办公用-器具-10000589,办公用品,器具,"Breville 炉灶, 白色",15671.040,10,0.4,-6791.960
5627,5651,US-2019-3360468,2019-08-04,2019-08-09,标准级,严盛-20410,严盛,消费者,宁波,浙江,中国,华东,家具-桌子-10001852,家具,桌子,"Bevis 会议桌, 组装",6908.384,4,0.6,-6908.496
4465,4487,CN-2018-5252007,2018-09-15,2018-09-20,标准级,常宣-20800,常宣,消费者,徐州,江苏,中国,华东,家具-桌子-10003847,家具,桌子,"Lesro 培训桌, 黑色",6021.120,12,0.6,-7978.320

,行 ID,订单 ID,订单日期,发货日期,装运模式,客户 ID,客户名称,细分,城市,省/自治区,国家/地区,区域,产品 ID,类别,子类别,产品名称,销售额,数量,折扣,利润
1,2,CN-2021-1973789,2021-06-15,2021-06-19,标准级,许安-10165,许安,消费者,内江,四川,中国,西南,办公用-信封-10004832,办公用品,信封,"GlobeWeis 搭扣信封, 红色",125.44,2,0.0,42.56
4,5,CN-2020-2975416,2020-05-31,2020-06-02,二级,万兰-15730,万兰,消费者,汕头,广东,中国,中南,办公用-器具-10003452,办公用品,器具,"KitchenAid 搅拌机, 黑色",1375.92,3,0.0,550.20
5,6,CN-2019-4497736,2019-10-27,2019-10-31,标准级,俞明-18325,俞明,消费者,景德镇,江西,中国,华东,技术-设备-10001640,技术,设备,"柯尼卡 打印机, 红色",11129.58,9,0.0,3783.78
6,7,CN-2019-4497736,2019-10-27,2019-10-31,标准级,俞明-18325,俞明,消费者,景德镇,江西,中国,华东,办公用-装订-10001029,办公用品,装订机,"Ibico 订书机, 实惠",479.92,2,0.0,172.76
7,8,CN-2019-4497736,2019-10-27,2019-10-31,标准级,俞明-18325,俞明,消费者,景德镇,江西,中国,华东,家具-椅子-10000578,家具,椅子,"SAFCO 扶手椅, 可调",8659.84,4,0.0,2684.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9946,9988,CN-2019-1608087,2019-08-13,2019-08-14,一级,贺斯-20935,贺斯云,消费者,哈尔滨,黑龙江,中国,东北,办公用-纸张-10004825,办公用品,纸张,"施乐 令, 回收",367.50,3,0.0,32.76
9947,9989,CN-2019-3773206,2019-01-10,2019-01-15,标准级,曹冬-12445,曹冬露,消费者,西安,陕西,中国,西北,办公用-装订-10000292,办公用品,装订机,"Wilson Jones 装订机盖, 实惠",156.66,3,0.0,51.66
9951,9993,CN-2019-3665640,2019-08-07,2019-08-14,标准级,邓黎-16465,邓黎明,消费者,随州,湖北,中国,中南,办公用-收纳-10002744,办公用品,收纳具,"Eldon 盒, 单宽度",192.08,4,0.0,22.96
9952,9994,US-2018-5128542,2018-05-23,2018-05-27,标准级,贺婉-21355,贺婉,公司,四平,吉林,中国,东北,技术-配件-10002428,技术,配件,"罗技 闪存驱动器, 回收",396.48,3,0.0,23.52
9955,9997,CN-2021-4318875,2021-05-28,2021-06-02,标准级,巩光-13435,巩光,消费者,义乌,浙江,中国,华东,办公用-收纳-10003383,办公用品,收纳具,"Eldon 盘, 蓝色",447.72,2,0.0,35.56

,行 ID,订单 ID,订单日期,发货日期,装运模式,客户 ID,客户名称,细分,城市,省份,国家/地区,区域,产品 ID,类别,子类别,产品名称,销售额,数量,折扣,利润
0,1,US-2021-1357144,2021-04-27,2021-04-29,二级,曾惠-14485,曾惠,公司,杭州,浙江,中国,华东,办公用-用品-10002717,办公用品,用品,"Fiskars 剪刀, 蓝色",129.696,2,0.4,-60.704
1,2,CN-2021-1973789,2021-06-15,2021-06-19,标准级,许安-10165,许安,消费者,内江,四川,中国,西南,办公用-信封-10004832,办公用品,信封,"GlobeWeis 搭扣信封, 红色",125.440,2,0.0,42.560
2,3,CN-2021-1973789,2021-06-15,2021-06-19,标准级,许安-10165,许安,消费者,内江,四川,中国,西南,办公用-装订-10001505,办公用品,装订机,"Cardinal 孔加固材料, 回收",31.920,2,0.4,4.200
3,4,US-2021-3017568,2021-12-09,2021-12-13,标准级,宋良-17170,宋良,公司,镇江,江苏,中国,华东,办公用-用品-10003746,办公用品,用品,"Kleencut 开信刀, 工业",321.216,4,0.4,-27.104
4,5,CN-2020-2975416,2020-05-31,2020-06-02,二级,万兰-15730,万兰,消费者,汕头,广东,中国,中南,办公用-器具-10003452,办公用品,器具,"KitchenAid 搅拌机, 黑色",1375.920,3,0.0,550.200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9954,9996,CN-2021-4318875,2021-05-28,2021-06-02,标准级,巩光-13435,巩光,消费者,义乌,浙江,中国,华东,技术-配件-10003923,技术,配件,"SanDisk 记忆卡, 实惠",944.244,3,0.4,-314.916
9955,9997,CN-2021-4318875,2021-05-28,2021-06-02,标准级,巩光-13435,巩光,消费者,义乌,浙江,中国,华东,办公用-收纳-10003383,办公用品,收纳具,"Eldon 盘, 蓝色",447.720,2,0.0,35.560
9956,9998,CN-2021-4318875,2021-05-28,2021-06-02,标准级,巩光-13435,巩光,消费者,义乌,浙江,中国,华东,家具-椅子-10002448,家具,椅子,"SAFCO 折叠椅, 红色",239.988,1,0.4,-88.032
9957,9999,CN-2021-4318875,2021-05-28,2021-06-02,标准级,巩光-13435,巩光,消费者,义乌,浙江,中国,华东,技术-配件-10002808,技术,配件,"罗技 路由器, 耐用",4851.588,7,0.4,-1617.392
9958,10000,CN-2018-3557528,2018-12-02,2018-12-06,标准级,陈忠-11470,陈忠,公司,温州,浙江,中国,华东,办公用-器具-10002023,办公用品,器具,"Breville 冰箱, 白色",7244.580,5,0.4,-3501.820

          销售额        数量        利润
销售额  1.000000  0.376575  0.473217
数量   0.376575  1.000000  0.151857
利润   0.473217  0.151857  1.000000

,行 ID,订单 ID,订单日期,发货日期,装运模式,客户 ID,客户名称,细分,城市,省/自治区,国家/地区,区域,产品 ID,类别,子类别,产品名称,销售额,数量,折扣,利润
5,6,CN-2019-4497736,2019-10-27,2019-10-31,标准级,俞明-18325,俞明,消费者,景德镇,江西,中国,华东,技术-设备-10001640,技术,设备,"柯尼卡 打印机, 红色",11129.580,9,0.0,3783.780
15,16,US-2020-2511714,2020-11-22,2020-11-25,一级,刘斯-20965,刘斯云,公司,徐州,江苏,中国,华东,办公用-器具-10003582,办公用品,器具,"KitchenAid 冰箱, 黑色",10336.452,7,0.4,-3962.728
49,50,CN-2021-2396895,2021-06-19,2021-06-22,二级配送,薛磊-15985,薛磊,消费者,蛟河,吉林,中国,东北,技术-电话-10004015,技术,电话,"思科 充电器, 全尺寸",12183.360,4,0.0,1340.080
52,53,CN-2020-2828982,2020-05-22,2020-05-26,标准级,苏晒-19825,苏晒明,消费者,青岛,山东,中国,华东,办公用-器具-10000297,办公用品,器具,"Hamilton Beach 炉灶, 黑色",12641.300,5,0.0,3539.200
150,151,CN-2019-5873075,2019-10-15,2019-10-20,二级配送,施丽-17380,施丽丽,公司,肇源,黑龙江,中国,东北,办公用-器具-10004829,办公用品,器具,"Breville 微波炉, 银色",15526.280,11,0.0,1085.700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9794,9836,CN-2019-2518780,2019-01-23,2019-01-28,标准级,丁妮-18610,丁妮,公司,昆明,云南,中国,西南,技术-复印-10002682,技术,复印机,"佳能 传真机, 每套两件",10697.904,9,0.2,668.304
9801,9843,US-2019-1436231,2019-12-03,2019-12-06,二级配送,贺立-16780,贺立,公司,襄樊,湖北,中国,中南,技术-电话-10004871,技术,电话,"三星 充电器, 蓝色",14249.760,8,0.4,-5700.800
9834,9876,CN-2020-4271574,2020-06-18,2020-06-22,标准级,赖虎-14035,赖虎,公司,南阳,河南,中国,中南,办公用-器具-10004675,办公用品,器具,"Hoover 炉灶, 白色",13220.900,5,0.0,0.000
9861,9903,CN-2018-4838467,2018-05-31,2018-06-03,一级,刘婵-10945,刘婵,消费者,巢湖,安徽,中国,华东,家具-椅子-10000578,家具,椅子,"SAFCO 扶手椅, 可调",10824.800,5,0.0,3355.100
9915,9957,CN-2018-2508741,2018-09-26,2018-09-28,一级,吕灵-17575,吕灵,消费者,哈尔滨,黑龙江,中国,东北,办公用-器具-10001154,办公用品,器具,"Hoover 冰箱, 银色",12296.900,5,0.0,983.500

6341