In [6]:
import numpy as np
import pandas as pd

In [7]:
data = [[1, 2, '2016-03-01', 5], [1, 2, '2016-05-02', 6], [2, 3, '2017-06-25', 1], [3, 1, '2016-03-02', 0], [3, 4, '2018-07-03', 5]]
activity = pd.DataFrame(data, columns=['player_id', 'device_id', 'event_date', 'games_played']).astype({'player_id':'Int64', 'device_id':'Int64', 'event_date':'datetime64[ns]', 'games_played':'Int64'})
first_login = activity.groupby("player_id")["event_date"].min().reset_index()
res = pd.merge(activity, first_login, on=["player_id", "event_date"])
res[["player_id", "device_id"]]

   player_id  device_id
0          1          2
1          2          3
2          3          1

In [8]:
data = [[5, 'show', 285, None, 1, 123], [5, 'answer', 285, 124124, 1, 124], [5, 'show', 369, None, 2, 125], [5, 'skip', 369, None, 2, 126]]
survey_log = pd.DataFrame(data, columns=['id', 'action', 'question_id', 'answer_id', 'q_num', 'timestamp']).astype({'id':'Int64', 'action':'object', 'question_id':'Int64', 'answer_id':'Int64', 'q_num':'Int64', 'timestamp':'Int64'})
show_cnt = survey_log[survey_log["action"] == "show"].groupby("question_id").size().reset_index(name="show_count")
ans_cnt = survey_log[survey_log["action"] == "answer"] \
    .groupby("question_id").size().reset_index(name="ans_count")
df = pd.merge(show_cnt, ans_cnt, on="question_id", how="left").fillna(0)
df["rate"] = df["ans_count"] / df["show_count"]
df = df.sort_values(by=["rate", "question_id"], ascending=[False, True])
res = df.head(1)[["question_id"]].rename(columns={"question_id": "survey_log"})
res

   survey_log
0         285