In [48]:
import numpy as np
import pandas as pd

In [49]:
data = [[1, 100], [2, 100], [3, 100]]
employee = pd.DataFrame(data, columns=['Id', 'Salary']).astype({'Id':'Int64', 'Salary':'Int64'})
N=2
newEmployee = employee.drop_duplicates(subset=['Salary'])
newEmployee
if len(newEmployee) >= N > 0:
    newEmployee.sort_values('Salary', ascending=False).iloc[[N-1],[1]].rename(columns={'Salary':f'getNthHighestSalary({N})'})
else:
    pd.DataFrame({f'getNthHighestSalary({N})':[np.nan]})

   Id  Salary
0   1     100

   getNthHighestSalary(2)
0                     NaN

In [50]:
data = [[1, 3.5], [2, 3.65], [3, 4.0], [4, 3.85], [5, 4.0], [6, 3.65]]
scores = pd.DataFrame(data, columns=['id', 'score']).astype({'id':'Int64', 'score':'Float64'})
scores['rank'] = scores['score'].rank(method='dense',ascending=False)
scores[['score','rank']].sort_values('rank')

   score  rank
2    4.0   1.0
4    4.0   1.0
3   3.85   2.0
1   3.65   3.0
5   3.65   3.0
0    3.5   4.0

In [51]:
data = [[1, 'Joe', 70000, 3], [2, 'Henry', 80000, 4], [3, 'Sam', 60000, None], [4, 'Max', 90000, None]]
employee = pd.DataFrame(data, columns=['id', 'name', 'salary', 'managerId']).astype({'id':'Int64', 'name':'object', 'salary':'Int64', 'managerId':'Int64'})
salary_map = employee.set_index('id')['salary']
employee[employee['salary'] > employee['managerId'].map(salary_map)][['name']]

  name
0  Joe

In [55]:
data = [[1, 2, '2016-03-01', 5], [1, 2, '2016-05-02', 6], [1, 3, '2017-06-25', 1], [3, 1, '2016-03-02', 0], [3, 4, '2018-07-03', 5]]
activity = pd.DataFrame(data, columns=['player_id', 'device_id', 'event_date', 'games_played']).astype({'player_id':'Int64', 'device_id':'Int64', 'event_date':'datetime64[ns]', 'games_played':'Int64'})
activity = activity.sort_values(['player_id', 'event_date'])
activity['games_played_so_far'] = activity.groupby('player_id')['games_played'].cumsum()
activity[['player_id', 'event_date', 'games_played_so_far']]

   player_id  device_id event_date  games_played  games_played_so_far
0          1          2 2016-03-01             5                    5
1          1          2 2016-05-02             6                   11
2          1          3 2017-06-25             1                   12
3          3          1 2016-03-02             0                    0
4          3          4 2018-07-03             5                    5

In [53]:
data = [[1, 2, '2016-03-01', 5], [1, 2, '2016-03-02', 6], [2, 3, '2017-06-25', 1], [3, 1, '2016-03-02', 0], [3, 4, '2018-07-03', 5]]
activity = pd.DataFrame(data, columns=['player_id', 'device_id', 'event_date', 'games_played']).astype({'player_id':'Int64', 'device_id':'Int64', 'event_date':'datetime64[ns]', 'games_played':'Int64'})
# 编写解决方案，报告在首次登录的第二天再次登录的玩家的比率，四舍五入到小数点后两位。换句话说，你需要计算从首次登录后的第二天登录的玩家数量，并将其除以总玩家数。
activity = activity.sort_values(['player_id', 'event_date'])
firstDate = activity.groupby('player_id')['event_date'].min()
diff = (activity['event_date'] - firstDate).dt.days
secondDay = activity.loc[diff == 1, 'player_id'].unique()
totlePlayer = activity['player_id'].unique()
pd.DataFrame({'fraction':[round(len(secondDay) / len(totlePlayer), 2)]})

   fraction
0      0.33

In [54]:
data = [[1, 'A'], [2, 'B'], [3, 'C'], [4, 'D'], [5, 'E']]
candidate = pd.DataFrame(data, columns=['id', 'name']).astype({'id':'Int64', 'name':'object'})
data = [[1, 2], [2, 4], [3, 3], [4, 2], [5, 5]]
vote = pd.DataFrame(data, columns=['id', 'candidateId']).astype({'id':'Int64', 'candidateId':'Int64'})
winnerId = vote['candidateId'].value_counts().idxmax()
candidate.loc[candidate['id']== winnerId, ['name']]

  name
1    B