In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
data = [[1, 'Joe'], [2, 'Henry'], [3, 'Sam'], [4, 'Max']]
customers = pd.DataFrame(data, columns=['id', 'name']).astype({'id': 'Int64', 'name': 'object'})
data = [[1, 3], [2, 1]]
orders = pd.DataFrame(data, columns=['id', 'customerId']).astype({'id': 'Int64', 'customerId': 'Int64'})
# customerId 是 Customers 表中 ID 的外键( Pandas 中的连接键)。   该表的每一行都表示订单的 ID 和订购该订单的客户的 ID。
# 找出所有从不点任何东西的顾客。输出的dataframe列名为Customers
# 找出所有从不点任何东西的顾客
customers[~customers['id'].isin(orders['customerId'])][['name']].rename(columns={'name': 'Customers'})

  Customers
1     Henry
3       Max

In [7]:
data = [[1, 'john@example.com'], [2, 'bob@example.com'], [3, 'john@example.com']]
person = pd.DataFrame(data, columns=['id', 'email']).astype({'id': 'int64', 'email': 'object'})
person.sort_values('id', inplace=True)
person.drop_duplicates(subset=['email'], inplace=True)
person

   id             email
0   1  john@example.com
1   2   bob@example.com

In [25]:
data = [[1, 2, '2016-03-01', 5], [1, 2, '2016-05-02', 6], [2, 3, '2017-06-25', 1], [3, 1, '2016-03-02', 0],
        [3, 4, '2018-07-03', 5]]
activity = pd.DataFrame(data, columns=['player_id', 'device_id', 'event_date', 'games_played']).astype(
    {'player_id': 'Int64', 'device_id': 'Int64', 'event_date': 'datetime64[ns]', 'games_played': 'Int64'})
activity.sort_values(['player_id', 'event_date']).groupby(by='player_id').min().reset_index()[
    ['player_id', 'event_date']].rename(columns={'event_date': 'first_login'})

   player_id first_login
0          1  2016-03-01
1          2  2017-06-25
2          3  2016-03-02

In [69]:
data = [[101, 'John', 'A', None], [102, 'Dan', 'A', 101], [103, 'James', 'A', 101], [104, 'Amy', 'A', 101],
        [105, 'Anne', 'A', 101], [106, 'Ron', 'B', 101]]
employee = (pd.DataFrame(data, columns=['id', 'name', 'department', 'managerId']).astype(
    {'id': 'Int64', 'name': 'object', 'department': 'object', 'managerId': 'Int64'}))
# 一行搞定
employee[employee['id'].isin(employee.groupby('managerId').size().loc[lambda s: s >= 5].index)][['name']]

   name
0  John

In [86]:
data = [[1, 100], [2, 200], [3, 300]]
employee = pd.DataFrame(data, columns=['id', 'salary']).astype({'id': 'int64', 'salary': 'int64'})
employee.sort_values('salary', inplace=True, ascending = False)
employee = employee.drop_duplicates(subset=['salary'])
if len(employee) >= 2 :
    result = pd.DataFrame({'SecondHighestSalary': [employee.iloc[1]['salary']]})
    result
else:
    result = pd.DataFrame({'SecondHighestSalary': [None]})
    result

   SecondHighestSalary
0                  200